version: '3.2'

services:
  db:
    image: "mariadb:10.5.3"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "123456"


  redis:
    restart: always
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis/data/redis-data:/data




  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080